// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Country struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Name   string `json:"name"`
}

type CountryInput struct {
	UserID int    `json:"userId"`
	Name   string `json:"name"`
}

type CountryResponse struct {
	Name string `json:"name"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
