definitions:
  entity.RegisterResponseFailure:
    properties:
      error:
        type: string
    type: object
  entity.RegisterResponseSuccess:
    properties:
      message:
        type: string
    type: object
  model.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Create New User with email and password
      parameters:
      - description: user's inforamtion
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.RegisterResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.RegisterResponseFailure'
      summary: Create New User
swagger: "2.0"
