definitions:
  entity.AddCountryRequest:
    properties:
      name:
        type: string
    type: object
  entity.CountryName:
    properties:
      name:
        type: string
    type: object
  entity.LoginResponseSuccess:
    properties:
      token:
        type: string
    type: object
  entity.Percentage:
    properties:
      value:
        type: string
    type: object
  entity.RegisterResponseSuccess:
    properties:
      message:
        type: string
    type: object
  entity.UserResponseFailure:
    properties:
      error:
        type: string
    type: object
  model.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /all-countries:
    get:
      consumes:
      - application/json
      description: Get all countries subscribed by the user
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.CountryName'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
      summary: Get all countries
  /country:
    post:
      consumes:
      - application/json
      description: Add new country for a the user
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: country name
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.AddCountryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.RegisterResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
      summary: Add new country
  /login:
    post:
      consumes:
      - application/json
      description: Login User with email and password
      parameters:
      - description: email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.LoginResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
      summary: Login
  /percentage-of-death-to-confirmed/{name}:
    get:
      consumes:
      - application/json
      description: get the percentage of death cases to confirmed cases for a given
        country.
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: country name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Percentage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
      summary: get the percentage of death cases to confirmed cases for a given country.
  /register:
    post:
      consumes:
      - application/json
      description: Create New User with email and password
      parameters:
      - description: email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.RegisterResponseSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
      summary: Create New User
  /top-three-countries/{type}:
    get:
      consumes:
      - application/json
      description: get the top 3 countries (among the subscribed countries) by the
        total number of cases based on the case type passed by the user (confirmed,
        death).
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: (confirmed, death)
        in: path
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.CountryName'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.UserResponseFailure'
      summary: Get Top Three Countries based on the case type passed by the user (confirmed,
        death)
swagger: "2.0"
